name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    permissions:
      contents: write
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      PROJECT_PATH: "GMLoader - xxHash\\GMLoader - xxHash.csproj"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Install Dotnet"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      #- name: "Restore packages"
      #  run: dotnet restore ${{ env.PROJECT_PATH }}
        
      #- name: "Build project"
      #  run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
        
      - run: pwd
      - run: dir "${{ env.PROJECT_PATH }}"
      - run: dir .
      - run: dir *.*
      - name: "Pack project"
        run: |
          dotnet build "${{ env.PROJECT_PATH }}" --configuration Release
          #rem dotnet pack "${{ env.PROJECT_PATH }}" -p:PackageVersion=4.0.5 --no-restore --no-build --configuration Release --include-symbols --output lib\Standart.Hash.xxHash.dll
          copy "GMLoader - xxHash\bin\Release\net8.0\GMLoader - xxHash.dll" "GMLoader\lib\Standart.Hash.xxHash.dll"
          dir GMLoader\lib\Standart.Hash.xxHash.dll

      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.0
        id: setup_msbuild
              
      - name: Run MSBuild
        id: run_msbuild
        run: |
          echo "Cleaning..."
          msbuild .\GMLoader\GMLoader.sln  /t:clean /p:Configuration=Debug
          echo "Installing dependencies..."
          nuget restore .\GMLoader\GMLoader.sln
          echo "Building GMLoader"
          msbuild .\GMLoader\GMLoader.sln  /t:build /p:Configuration=Debug

      #- name: Upload built exe
      #  if: success()
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: snapshot.${{ env.VERSION }}.zip
      #    path: |
      #        D:\a\voicebox-feature-rocm-windows-support\voicebox-feature-rocm-windows-support\tauri\src-tauri\target\release\voicebox.exe
      #        D:\a\voicebox-feature-rocm-windows-support\voicebox-feature-rocm-windows-support\tauri\src-tauri\target\release\voicebox-server.exe
